---

- set_fact:
    role_comment: "( {{ docker_container_name | default('jenkins') }} )"

- name: ensure container is started {{ role_comment }}
  include_role:
    name: aem_design.docker_container
  vars:
    env:
      TZ: "{{ docker.timezone }}"
      JAVA_ARGS: "{{ service_jvm_opts }}"
  tags:
    - docker-container

- name: update host network iptables {{ role_comment }}
  include_role:
    name: aem_design.config_iptables
  tags:
    - host-config

- name: wait until service is ready {{ role_comment }}
  uri:
    url: "http://{{ service_jenkins_address }}:{{ service_jenkins_http_port }}"
    return_content: yes
    timeout: 300
    status_code: 403
  register: service_console
  until: service_console.content.find('You are authenticated as') != -1
  delay: "{{ wait_delay | default(5) }}"
  retries: 360
