---
- name: Converge
  hosts: instance
  become: true
  vars:
    local_role_name: "ansible-role-jenkins"
    role_name: "{% if lookup('env','ROLE_NAME_FULL') %}{{ lookup('env','ROLE_NAME_FULL') }}{% else %}{{ local_role_name }}{% endif %}"
    test_container_name: "{{ local_role_name }}-test"

  pre_tasks:
    - name: get docker host ip
      become: true
      shell: |
        set -o pipefail
        /sbin/ip route | awk '/default/ { print $3 }'
      args:
        executable: /bin/bash
      register: dockerhost_ip
      changed_when: false

  roles:
    - {
      role: "{{ role_name }}",
      service_jenkins_host: "{{ dockerhost_ip.stdout }}",
      docker_container_name: "{{ test_container_name }}",
      debug_hide: false,
      docker_host: "unix://tmp/docker.sock"
    }
